# SITE SETTINGS (Custom variables accessible in templates via {{ site.myvariable }})

# Title and URL
title: Michael Fryar
url: http://mefryar.github.io

# One post per page
paginate: 1

# Contact information for Atom
author:
  name: Michael Fryar
  email: michaelefryar@gmail.com

# Google Analytics Measurement ID
google_analytics_measurement_id: G-9C8NT6XM05

# BUILD SETTINGS

# Pretty style Permalinks (/:categories/:year/:month/:day/:title/)
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Minify compiled CSS (Removes unnecessary characters for faster loading)
sass:
  style: :compressed

